import './globals.css';
import { Inter } from 'next/font/google';
import connectDB from '@/utils/database';
import { Provider } from '@/context/Provider';
import Link from 'next/link';

connectDB();

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  metadataBase: new URL('https://nextjs-server-action.vercel.app'),
  title: {
    default: 'Next.js SEO | DevAT Korea',
    template: `%s | Next.js SEO | DevAT Korea`,
  },
  description: 'Generated by create next app',
  generator: 'Next.js',
  applicationName: 'Next.js SEO',
  referrer: 'origin-when-cross-origin',
  keywords: ['Next.js', 'React', 'JavaScript', 'DevAT Korea'],
  authors: [{ name: 'DevAT Korea' }, { name: 'DevAT Korea', url: 'https://nextjs.org' }],
  colorScheme: 'lite',
  creator: 'you',
  publisher: 'you',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    title: 'Next.js SEO | DevAT-Korea',
    description: 'The React Framework for the Web',
    images: [
      {
        url: '/open_image.png',
        width: 400,
        height: 300,
      },
    ],
  },
  verification: {
    google: 'google',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{ display: 'flex', gap: '20px' }}>
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          <Link href="/admin">Admin</Link>
        </header>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
